spring:
  datasource:
    url: jdbc:h2:/tmp/dev.db;AUTO_SERVER=true
    username: user
    password: user
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect